<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            [
                'slug' => 'veillee-toute-la-nuit',
                'title' => 'Veillée de prière « Toute la nuit »',
                'type' => 'Veillée',
                'location' => 'Temple central · Yopougon Ficgayo',
                'host' => "Département d'intercession",
                'start_date' => '2026-06-27 22:00:00',
                'end_date' => '2026-06-28 05:00:00',
                'description' => 'Une nuit entière dans la présence de Dieu : adoration, intercession et combat spirituel.',
                'highlights' => ["Temps d'adoration prolongée", 'Intercession ciblée par thèmes', 'Ministration et prière individuelle', 'Petit-déjeuner de communion à l’aube'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'culte-action-de-grace',
                'title' => "Culte d'action de grâce",
                'type' => 'Culte',
                'location' => 'Temple central · Yopougon Ficgayo',
                'host' => 'Pasteur David Odion Victor',
                'start_date' => '2026-06-29 09:00:00',
                'end_date' => null,
                'description' => 'Un dimanche pour rendre grâce à Dieu pour sa fidélité et témoigner des bénédictions reçues.',
                'highlights' => ['Louange & adoration en direct', 'Témoignages de la Maison', "Message d'action de grâce"],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'seminaire-des-couples',
                'title' => 'Séminaire des couples',
                'type' => 'Séminaire',
                'location' => 'Salle des fêtes · Cocody Angré',
                'host' => 'Ministère Couples & Familles',
                'start_date' => '2026-07-05 15:00:00',
                'end_date' => null,
                'description' => "Un après-midi d'enseignement et d'ateliers interactifs pour bâtir des foyers solides.",
                'highlights' => ['Enseignement biblique sur le couple', 'Ateliers de communication', "Temps d'échange et de prière"],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'maison-de-feu-2026',
                'title' => 'Conférence « Maison de Feu 2026 »',
                'type' => 'Conférence',
                'location' => 'Temple central · Yopougon Ficgayo',
                'host' => 'Orateurs invités',
                'start_date' => '2026-07-11 09:00:00',
                'end_date' => '2026-07-13 21:00:00',
                'description' => "Trois jours de prière intense, d'adoration prophétique et d'enseignements percutants avec des orateurs nationaux et internationaux.",
                'highlights' => ['Sessions plénières matin & soir', 'Soirées de miracle et de réveil', 'Ateliers thématiques', 'Grande célébration finale'],
                'is_featured' => true,
                'image_path' => null,
            ],
            [
                'slug' => 'concert-adoration-choeurs-en-feu',
                'title' => "Concert d'adoration « Chœurs en Feu »",
                'type' => 'Concert',
                'location' => 'Temple central · Yopougon Ficgayo',
                'host' => 'Ministère Louange & Adoration',
                'start_date' => '2026-07-19 16:30:00',
                'end_date' => '2026-07-19 20:00:00',
                'description' => 'Une rencontre de louange et d’adoration pour magnifier le Seigneur à travers le chant.',
                'highlights' => ['Prestation de la chorale principale', 'Artistes invités de renom', 'Atmosphère de louange prophétique'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'rentree-ecole-du-dimanche-2026',
                'title' => "Rentrée solennelle de l'Éco-Dim",
                'type' => 'Spécial enfants',
                'location' => 'Salle des enfants · MFM Ficgayo',
                'host' => 'Moniteurs Éco-Dim',
                'start_date' => '2026-09-06 09:00:00',
                'end_date' => '2026-09-06 11:30:00',
                'description' => 'C’est la rentrée ! Accueillons nos enfants pour une nouvelle année de croissance spirituelle et de jeux.',
                'highlights' => ['Distribution de fournitures', 'Spectacle de marionnettes', 'Prière de bénédiction pour l’année scolaire'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'retraite-jeunesse-generation-feu',
                'title' => 'Retraite spirituelle « Génération Feu »',
                'type' => 'Retraite',
                'location' => 'Centre de retraite · Bingerville',
                'host' => 'Jeunesse « Génération Feu »',
                'start_date' => '2026-08-14 08:00:00',
                'end_date' => '2026-08-16 17:00:00',
                'description' => 'Trois jours de retraite en dehors de la ville pour se ressourcer, prier et partager des moments fraternels forts.',
                'highlights' => ['Études bibliques approfondies', 'Veillées de feu et de consécration', 'Activités sportives et récréatives'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'seminaire-formation-leaders',
                'title' => 'Séminaire de formation des leaders',
                'type' => 'Formation',
                'location' => 'Salle de conférence · MFM Ficgayo',
                'host' => 'Comité de Direction',
                'start_date' => '2026-07-25 09:00:00',
                'end_date' => '2026-07-25 13:00:00',
                'description' => 'Un séminaire intensif destiné à équiper les responsables de départements et de cellules.',
                'highlights' => ['Principes de leadership biblique', 'Gestion administrative et communication', 'Prière et onction de service'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'louange-non-stop-12h',
                'title' => '12h de louange non-stop',
                'type' => 'Célébration',
                'location' => 'Esplanade du Temple · MFM Ficgayo',
                'host' => 'Groupe de Louange central',
                'start_date' => '2026-08-01 08:00:00',
                'end_date' => '2026-08-01 20:00:00',
                'description' => 'Une journée entière dédiée à la louange et à l’adoration continues sans interruption.',
                'highlights' => ['12 chorales et groupes différents', 'Lecture publique de la Parole', 'Moments de prière pour la nation'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'culte-special-pentecote',
                'title' => 'Culte spécial du Saint-Esprit',
                'type' => 'Culte spécial',
                'location' => 'Temple central · Yopougon Ficgayo',
                'host' => 'Collège Pastoral',
                'start_date' => '2026-06-21 09:00:00',
                'end_date' => null,
                'description' => 'Un culte mémorable célébrant l’effusion du Saint-Esprit et la puissance de la Pentecôte.',
                'highlights' => ['Adoration prophétique', 'Baptême du Saint-Esprit', 'Message sur le réveil spirituel'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'evangelisation-yopougon-2026',
                'title' => 'Grande campagne d’évangélisation',
                'type' => 'Évangélisation',
                'location' => 'Terrain Ficgayo · Yopougon',
                'host' => 'Département Évangélisation',
                'start_date' => '2026-08-22 17:00:00',
                'end_date' => '2026-08-22 21:00:00',
                'description' => 'Une soirée de proclamation de l’Évangile avec prière pour les malades et salut des âmes.',
                'highlights' => ['Chantres de réveil', 'Prédication de l’Évangile de grâce', 'Prière de délivrance et de guérison'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'veillee-nationale-delivrance',
                'title' => 'Veillée nationale de délivrance',
                'type' => 'Veillée',
                'location' => 'Temple central · Yopougon Ficgayo',
                'host' => 'Département de Délivrance',
                'start_date' => '2026-08-28 22:00:00',
                'end_date' => '2026-08-29 05:30:00',
                'description' => 'Une nuit de brisement des liens familiaux, de restauration spirituelle et de délivrance.',
                'highlights' => ['Enseignement sur le combat spirituel', 'Séances de délivrance de masse', 'Onction d’huile sainte'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'conference-femmes-vertueuses',
                'title' => 'Conférence des Femmes Vertueuses',
                'type' => 'Conférence',
                'location' => 'Temple central · Yopougon Ficgayo',
                'host' => 'Département des Femmes',
                'start_date' => '2026-09-12 14:00:00',
                'end_date' => '2026-09-12 18:30:00',
                'description' => 'Une rencontre inspirante pour encourager les femmes à briller dans leur foyer, église et vie professionnelle.',
                'highlights' => ['Panel de discussion interactif', 'Enseignement sur l’impact féminin', 'Prière de consécration des familles'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'journee-veuves-orphelins-2026',
                'title' => 'Journée de solidarité et d’amour',
                'type' => 'Actions sociales',
                'location' => 'Esplanade du Temple · MFM Ficgayo',
                'host' => 'Ministère d’entraide sociale',
                'start_date' => '2026-09-20 10:00:00',
                'end_date' => '2026-09-20 15:00:00',
                'description' => 'Une journée d’entraide pour apporter soutien matériel, réconfort spirituel et cadeaux aux veuves et orphelins.',
                'highlights' => ['Distribution de denrées et vêtements', 'Repas communautaire fraternel', 'Moment de prière et d’encouragement'],
                'is_featured' => false,
                'image_path' => null,
            ],
            [
                'slug' => 'foire-culinaire-fraternelle-2026',
                'title' => 'Foire fraternelle et culinaire',
                'type' => 'Communion',
                'location' => 'Cour de l’église · MFM Ficgayo',
                'host' => 'Comité d’organisation',
                'start_date' => '2026-09-27 12:00:00',
                'end_date' => '2026-09-27 18:00:00',
                'description' => 'Venons partager un repas ensemble ! Stands gastronomiques, jeux de kermesse et communion fraternelle.',
                'highlights' => ['Spécialités culinaires ivoiriennes', 'Jeux gonflables pour enfants', 'Grand quiz biblique par équipe'],
                'is_featured' => false,
                'image_path' => null,
            ],
        ];

        foreach ($events as $event) {
            Event::updateOrCreate(['slug' => $event['slug']], $event);
        }
    }
}
